name = "terminal"
version = "versionplaceholder"
sofile = "terminal.so"
permission = [
"Create terminal",
"Access terminal",
"Modify terminal",
"Delete terminal",
]
scope = [
"profile",
]
dependency = []
